version: '3'

services:
  master:
    container_name: master
    image: ros:kinetic-ros-base
    network_mode: host
    command: roscore
  imu_piksy_drivers:
    depends_on:
      - master
    container_name: drivers
    image: earthrover/earth_rover_localization:0.0.1
    network_mode: host
    privileged: true
    command: >
      /bin/bash -c "
        sleep 2;
        roslaunch earth_rover_localization imu_piksy_drivers.launch;
      "